version: '3'

services:
  fronend:
    # build: ./vue
    image: tesla59/laravel_vue-front:1
    container_name: frontend
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - backend
      - mysql
    environment:
      - VITE_API_BASE_URL=http://backend:8000

  backend:
    # build: .
    image: tesla59/laravel_vue-back:1
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.29
    container_name: mysql
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
        - ./init.sql:/data/application/init.sql
    networks:
      - app-network
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
  
  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: phpmyadmin
    ports:
      - 8081:80
    networks:
      - app-network
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1

  redis:
    image: redis:7.0.3
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
